/**
 *
 */
import { User } from './User';

export class UserModel implements User {
	userId?: number; // Optional because it's auto-generated by the database
	name: string; // Required
	email: string; // Required
	passwordHash: string; // Required
	phone?: string;
	addressStreet?: string;
	addressComplement?: string;
	addressProvince?: string;
	addressCountry?: string;
	addressPostalCode?: string;
	role?: 'customer' | 'admin';
	createdAt?: Date;
	updatedAt?: Date;

	constructor(user: User) {
		this.userId = user.userId;
		this.name = user.name;
		this.email = user.email;
		this.passwordHash = user.passwordHash;
		this.phone = user.phone;
		this.addressStreet = user.addressStreet;
		this.addressComplement = user.addressComplement;
		this.addressProvince = user.addressProvince;
		this.addressCountry = user.addressCountry;
		this.addressPostalCode = user.addressPostalCode;
		this.role = user.role || 'customer'; // Default role
		this.createdAt = user.createdAt;
		this.updatedAt = user.updatedAt;
	}

	// Getters
	getUserId(): number | undefined {
		return this.userId;
	}

	getName(): string {
		return this.name;
	}

	getEmail(): string {
		return this.email;
	}

	getPasswordHash(): string {
		return this.passwordHash;
	}

	getPhone(): string | undefined {
		return this.phone;
	}

	getAddressStreet(): string | undefined {
		return this.addressStreet;
	}

	getAddressComplement(): string | undefined {
		return this.addressComplement;
	}

	getAddressProvince(): string | undefined {
		return this.addressProvince;
	}

	getAddressCountry(): string | undefined {
		return this.addressCountry;
	}

	getAddressPostalCode(): string | undefined {
		return this.addressPostalCode;
	}

	getRole(): 'customer' | 'admin' | undefined {
		return this.role;
	}

	getCreatedAt(): Date | undefined {
		return this.createdAt;
	}

	getUpdatedAt(): Date | undefined {
		return this.updatedAt;
	}

	// Setters
	setUserId(userId: number | undefined): void {
		this.userId = userId;
	}

	setName(name: string): void {
		this.name = name;
	}

	setEmail(email: string): void {
		this.email = email;
	}

	setPasswordHash(passwordHash: string): void {
		this.passwordHash = passwordHash;
	}

	setPhone(phone: string | undefined): void {
		this.phone = phone;
	}

	setAddressStreet(addressStreet: string | undefined): void {
		this.addressStreet = addressStreet;
	}

	setAddressComplement(addressComplement: string | undefined): void {
		this.addressComplement = addressComplement;
	}

	setAddressProvince(addressProvince: string | undefined): void {
		this.addressProvince = addressProvince;
	}

	setAddressCountry(addressCountry: string | undefined): void {
		this.addressCountry = addressCountry;
	}

	setAddressPostalCode(addressPostalCode: string | undefined): void {
		this.addressPostalCode = addressPostalCode;
	}

	setRole(role: 'customer' | 'admin' | undefined): void {
		this.role = role;
	}

	setCreatedAt(createdAt: Date | undefined): void {
		this.createdAt = createdAt;
	}

	setUpdatedAt(updatedAt: Date | undefined): void {
		this.updatedAt = updatedAt;
	}

	/**
	 * @returns {string} of the object's attributes.
	 */
	toString(): string {
		return `UserModel {
			userId: ${this.userId ?? 'N/A'},
			name: ${this.name},
			email: ${this.email},
			phone: ${this.phone ?? 'N/A'},
			addressStreet: ${this.addressStreet ?? 'N/A'},
			addressComplement: ${this.addressComplement ?? 'N/A'},
			addressProvince: ${this.addressProvince ?? 'N/A'},
			addressCountry: ${this.addressCountry ?? 'N/A'},
			addressPostalCode: ${this.addressPostalCode ?? 'N/A'},
			role: ${this.role ?? 'customer'},
			createdAt: ${this.createdAt ? this.createdAt.toISOString() : 'N/A'},
			updatedAt: ${this.updatedAt ? this.updatedAt.toISOString() : 'N/A'}
		}`;
	}
}
